name: Continuous Integration

on:
    pull_request:
    push:
        branches:
            - main
            - 'releases/*'

jobs:
    test-action:
        name: GitHub Actions Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4

            - name: Test Local Action
              id: test-action
              uses: ./
              env:
                  JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
                  JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

            - name: Print Output
              id: output
              run: echo "${{ steps.test-action.outputs.time }}"
